name: inventory_management_app
description: "A new Flutter project."
publish_to: 'none' # Private package, will not publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # iOS style icons
  cupertino_icons: ^1.0.8

  # State management and routing
  get: 4.7.3

  # Local storage
  shared_preferences: ^2.2.3

  # ðŸ“„ PDF generation (Bill / Invoice)
  pdf: ^3.10.4

  # ðŸ“ File path access (required for PDF save)
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints for Flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/

  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700
